global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]  # Kafka exporter metrics
  - job_name: 'redpanda'
    static_configs:
      - targets: [ 'redpanda:8080' ]  # Redpanda metrics (optional)
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]  # Prometheus self-monitoring